#! /bin/bash

# Hello! Welcome to the Pet Diary Tooling or pdt for short!
# This tooling is designed to make the development process a bit easier.

source ./tooling.sh

pdt-help() {
    echo " ____  ____ _____ "
    echo "|  _ \|  _ \_   _|"
    echo "| |_) | | | || |  "
    echo "|  __/| |_| || |  "
    echo "|_|   |____/ |_|  "
    echo
    echo "Pet Diary Tooling"
    echo
    echo "Hi, you've found the help thingy-ma-bob!"
    echo "Enter the command 'pdt' if you wish to see this message again."
    echo "You will also see this message anytime you fail to spell a pdt"
    echo "command correctly too."
    echo
    echo "Usage: pdt [COMMAND]"
    echo
    echo "COMMANDS:"
    echo
    echo "    aws-login"
    echo "        This logs you in via SSO using the variables set up in"
    echo "	  configure-vars"
    echo
    echo "    sam-check"
    echo "        This will run checks against your sam-template"
    echo
    echo "    sam-deploy"
    echo "        This will deploy you application"
    echo
    echo "    sam-destroy"
    echo "        This will tear down the application leaving nothing in AWS"
    echo
    echo "    python-lint"
    echo "        This will lint your Python code using flake8,"
    echo "        it will start in the current directory and exclude the venv"
    echo
    echo "    python-security-check"
    echo "        This will run Bandit on the app/ directory. Bandit scans your"
    echo "        Python code for secuirty issues, it does not check any"
    echo "        imported or installed libraries for secuirty flaws though."
    echo
    echo "    python-test"
    echo "        This will run pytest against the tests/ directory in very"
    echo "        verbose mode"
    echo
    echo "    configure-vars"
    echo "        This will parse your AWS config file and let you choose which"
    echo "        profile and region you wish to use when running functions"
    echo "        which require AWS usage (e.g. sam-deploy)"
    echo
    echo "    configure-venv"
    echo "        This will set up your virtual environment for you,"
    echo "        it is the reccomended way to do so"
    echo
    echo "    full-security-check"
    echo "        This will run each of the security checks consecutively and"
    echo "        can be redirected into a text file to form a security audit"
    echo "        report."
    echo "        The included security checks are:"
    echo "            - Bandit (for Python code)"
    echo "            - Checkov (for SAM template)"
}


pdt() {
    case "$1" in
        "aws-login")
            aws-login
            ;;
        "sam-check")
            sam-check
            ;;
        "sam-deploy")
            sam-deploy
            ;;
        "sam-destroy")
            sam-destroy
            ;;
        "python-lint")
            python-lint
            ;;
        "python-test")
            python-test
            ;;
        "python-security-check")
            python-security-check
            ;;
        "configure-vars")
            configure-vars
            ;;
        "configure-venv")
            configure-venv
            ;;
        "full-security-check")
            full-security-check
            ;;
        *)
            pdt-help
            ;;
    esac
}

pdt "$1"
