name: Investigations

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: env
      run: |
        env
    - name: pwd
      run: |
        pwd
    - name: ls ..
      run: |
        ls ..
