name: Security Check

on: [push]

jobs:
  Security_Report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Set up venv
      run: |
        . ./pdt configure-venv
    - name: Installing Grype
      run: |
        . ./pdt activate && . ./pdt install-anchore-security-tools
    - name: Running security report
      run: |
        . ./pdt activate && . ./pdt full-security-check
