name: SecurityCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installing Grype
      run: |
        cat ./install-scripts/grype-install.sh | sudo sh -s -- -b /usr/local/bin
    - name: Running security report
      run: |
        . ./pdt full-security-check
