name: SecurityCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installing Grype
      run: |
        . ./pdt install-anchore-security-tools
    - name: Running security report
      run: |
        . ./pdt full-security-check
