name: Security Check

on: [push]

jobs:
  Security_Report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up venv
      run: |
        . ./pdt configure-venv
    - name: Installing Grype
      run: |
        . ./pdt activate && . ./pdt install-anchore-security-tools
    - name: Running security report
      run: |
        . ./pdt activate && . ./pdt full-security-check
