name: SecurityCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up venv
      run: |
        . ./pdt configure-venv
    - name: Installing Grype
      run: |
        cat ./installation-files/grype-install.sh | sudo sh -s -- -b /usr/local/bin
    - name: Install SAM CLI
      run: |
        ./installation-files/aws-sam/install
    - name: Running security report
      run: |
        . ./pdt full-security-check
